Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,11 +56,17 @@ jobs:
           Get-ChildItem -Path .\src -Recurse -Filter *.py -Exclude '__init__.py' | `
           ForEach-Object { Rename-Item $_.FullName -NewName ($_.FullName -replace '\.py$', '.pyx') }
 
+      - name: Ensure dist directory
+        run: mkdir -p dist
+
       - name: Build Cython
         run: |
-          python setup.py build_ext --inplace
+          python setup.py build_ext --inplace || echo "Build failed!"
           Get-ChildItem -Path .\src -Recurse -Filter *.pyx | ForEach-Object { Remove-Item $_.FullName }
           Get-ChildItem -Path .\src -Recurse -Filter *.cpp | ForEach-Object { Remove-Item $_.FullName }
+
+      - name: Debug Build Path
+        run: ls -lR ./
 
       - name: Run tests
         run: |
@@ -71,6 +77,7 @@ jobs:
 
       - name: Build Executable
         run: |
+          if (!(Test-Path "dist")) { Write-Host "Error: dist directory not found!"; exit 1 }
           python -m ok.update.package_launcher ${{ github.ref_name }} deploy.txt
           Copy-Item -Path "dist" -Destination "gathering-wives" -Recurse
           7z a -t7z -r "gathering-wives-${{ github.ref_name }}.7z" "gathering-wives"
